server:
  port: 10060

spring:
  application:
    name: redis-grey
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis: #换集群需要换配置，测试环境为单机
    host: 172.19.0.2
    port: 6379
    password: iZ6LrKVA!6zqRDMNm4
    database: 6
    #超时时间
    timeout: 3600ms
    #jedis连接池
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 9
        # 连接池中的最小空闲连接
        min-idle: 2
  rabbitmq:
    url: amqp://172.19.0.25:5672
    host: 172.19.0.25
    port: 5672
    username: boss-dev
    password: tXSRJvPtTfgQob1e
    virtual-host: boss-dev
    #开启 return机制
    publisher-returns: true
    #开启confirm机制
    publisher-confirms: true
  #  publisher-confirm-type: correlated  新版本的开启confirm机制
  #人工确认
    listener:
      direct:
         acknowledge-mode: manual
      simple:
          acknowledge-mode: manual
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1dzuicg4dy1izu0ro.mysql.rds.aliyuncs.com:3306/redis-grey?useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: persagy@2021
    #需要优化连接池配置，满足线上需要
    hikari:
      #最小空闲数，线上环境需要调整
      minimumIdle: 3
      # 最大连接数，线上环境需要调整
      maximumPoolSize: 30
      # 空闲时间 3 min
      idleTimeout: 180000
      #获取连接超时时间 30s
      connectionTimeout: 30000
      #连接池中连接最大生命周期 30min
      max-lifetime: 1800000
  jta:
    bitronix:
      datasource:
        enable-jdbc4-connection-test:


feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000

logging:
  file: /boss-strategy-logs/${spring.application.name}/root.log
  level:
    root: INFO

mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/strategy/*.xml
  global-config:
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
  configuration:
    #配置数据库下划线和java驼峰属性映射
    map-underscore-to-camel-case: true
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
boss:
  properties:
    #   开启快速失败
    validatorEnable: false
    #　 启用aop log
    aopLogEnable: false
    #   开启登录拦截器
    loginInterceptorEnable: false

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

swagger:
  enable: true

redis:
  key:
    prefix: dev-boss-strategy


## 腾讯TCT定时任务
tct:
  # 默认是 false 不启用。本地启动服务时设置为false
  enabled: false


